FROM python:3.11-slim

ARG MODEL_PATH
ARG MODEL_NAME

ENV CATDOG_MODEL_LOCATION=/app/${MODEL_NAME}
ENV CATDOG_HOST=0.0.0.0
ENV CATDOG_PORT=8080

RUN conda install -y mkl mkl-service intel-openmp

RUN conda install -y python=3.11 flask waitress \
 && pip install torch torchvision --index-url https://download.pytorch.org/whl/cpu \
 && mkdir -p /app

WORKDIR /app 
COPY ./model.py /app/
COPY ./catdog_server.py /app/
COPY ${MODEL_PATH}/${MODEL_NAME} /app/
COPY ./run-model-service.sh /run-model-service.sh 
RUN chmod +x /run-model-service.sh 

EXPOSE 8080
ENTRYPOINT ["/run-model-service.sh"] 

